#!/bin/sh

test -f /etc/profile && . /etc/profile
test -f $HOME/.profile && . $HOME/.profile

systemctl --user import-environment

if test -f $HOME/.xsession ; then
    exec systemd-run --user --wait $HOME/.xsession
else
    exec systemd-run --user --wait xterm
fi
