#!/bin/sh

test -f /usr/bin/j-session && rm /usr/bin/j-session
test -f /usr/sbin/j-login && rm /usr/sbin/j-login
test -f /usr/sbin/j-login-setup && rm /usr/sbin/j-login-setup
test -f /usr/sbin/j-login-sleep && rm /usr/sbin/j-login-sleep
test -f /usr/share/applications/log-out.desktop && rm /usr/share/applications/log-out.desktop
test -f /usr/share/applications/switch-user.desktop && rm /usr/share/applications/switch-user.desktop
test -f /usr/share/pixmaps/j-login.png && rm /usr/share/pixmaps/j-login.png

update-desktop-database
